{{- if .Values.certManager.enabled -}}
{{- $fullname := include "proxy-internet.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
  labels:
    {{- include "proxy-internet.labels" . | nindent 4 }}
spec:
  vault:
    server: {{ .Values.certManager.vaultPKI.server | quote }}
    path: {{ .Values.certManager.vaultPKI.path | quote }}
    auth:
      kubernetes:
        mountPath: {{ .Values.certManager.vaultPKI.authPath | quote }}
        role: {{ .Values.certManager.vaultPKI.role | quote }}
        serviceAccountRef:
          name: {{ .Values.certManager.vaultPKI.serviceAccountRef | quote }}
{{- end }}
