{{- if not .Values.minio.existingSecret -}}
{{- $fullname := include "proxy-internet.fullname" . -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "proxy-internet.minioSecretName" . }}
  labels:
    {{- include "proxy-internet.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{ include "proxy-internet.minioSecretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: kv/services/minio
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: kv/services/minio
        property: secret-key
{{- end }}
