{{- if and .Values.helmSync.enabled (not .Values.harbor.existingSecret) -}}
{{- $fullname := include "proxy-internet.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy-internet.harborSecretName" . }}
  labels:
    {{- include "proxy-internet.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.harbor.user | quote }}
  password: {{ .Values.harbor.pass | quote }}
{{- end }}
