{{- $fullname := include "proxy-internet.fullname" . -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  labels:
    {{- include "proxy-internet.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.certManager.vaultPKI.server | quote }}
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.certManager.vaultPKI.authPath | quote }}
          role: proxy-internet
