---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxy-internet
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: infra-platform-services
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.aegisgroup.ch/infra_and_platform_services/harvester-proxy-internet-vm.git
    targetRevision: main
    path: proxy-internet-k8s-service/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: proxy-internet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
        - /metadata/labels
        - /metadata/annotations
        - /metadata/ownerReferences
